### ISSUE TITLE
Request: Staff editor / color changer

### ISSUE THREAD

**Issue by GLlZZYGUZZLER** [goatfungus/NMSSaveEditor#1020]
Just thought it'd be nice to easily pick and choose voltaic staff (multitool) parts and colors. :]

**Comment by jdm12983** [comment]
I am not sure that would be possible.

Most that could be done would be to enter different "Seed" codes to change the look (if that effects the look the same way it does for the "gun" multi tools and ships). Otherwise, you will just need to add the separate parts into your inventory through the save editor and build a new one.
