### ISSUE TITLE
Use of "backups" folder

### ISSUE THREAD

**Issue by waldo3000** [goatfungus/NMSSaveEditor#110]
On newer versions of NMSSE, it moves all zip files in the save directory with "backup" in its name into a NMSSE subfolder called "backups". This is done for both zip files NMSSE creates AND for other user-created zip files named "backup ***.zip"

I would strongly recommend that you not do that.  I suppose you are try to better organize the backups from previous versions of NMSSE, but this creates problems.  I backup save files to zip files named "backup MM-DD-YY.zip" and recently they all mysteriously disappeared.  It took me a while to find them since I had no idea NMSSE was moving them to its own folder.  Fortunately, I had not yet deleted the old NMSSE folder [I keep each version in a separate folder in case I need to revert].  If I had, all my old backups would be gone.

====================================

BTW,  you closed the issue of hanging when encountering invalid ASCII, but 1.5.20 seems to work for me.

**Comment by goatfungus** [comment]
Ah, sorry about that.... the editor actually checks whether the filename starts with "backup" and ends with ".zip", as those were all detected as valid backup files previously. Since your naming scheme is the same as the one the editor uses for backup files, you would probably have noticed that your manual backups used to appear in the file selection dropdown even though they would throw an error if you opened them. I would suggest using a different scheme, or backup the whole directory in the parent folder instead. Now at least you can do that without also backing up all the editor backups.

As for #98 that I closed.... I thought the solution in 1.5.20 would fix the issue, so I closed it and left a note. I don't always get confirmation from users that any changes have resolved an issue, so I usually just close them off and if the problem persists they can always reopen them with an updated description. If you can imagine, there have been over 100 issues logged so far, so the list could get pretty long if I don't do this.

**Comment by waldo3000** [comment]
I guess I see it differently.  Anytime a software program of any kind moves user files to another directory without the user's knowledge or consent, it's a pretty rude thing to do, especially if those files are not created by your software.

And my backup files did not show up in the file selection dropdown - the files are moved before the main screen is shown.  There was no way I would have had known that NMSSE was even to blame for moving my files.  If I hadn't been experimenting with saved files trying to understand the UTF-8 issue, I would not have been using the program enough to have discovered that the problem was caused by NMSSE.  I had even gotten to the point where I did a hard drive diagnostic to try to pin down why my files were vanishing.

**Comment by goatfungus** [comment]
I meant prior to the update that introduced the move feature. The same logic that moved the files was used previously to make them show in the dropdown box. You can always pull an older version if you don't believe me.

I made an assumption that people wouldn't be doing anything that could cause conflicts with the editor, such as using the same filename pattern as the ones I used since Atlas Rises for their own separate backups and storing them in the same directory. The editor was never supposed to handle such a scenario.

I would strongly recommend that in the future you do not store your own backups in that directory even if you weren't using the backup*.zip file pattern, because that directory is meant for save game files created by NMS only.

I am glad you were able to find them again though, so can we close this one off now?
