### ISSUE TITLE
Suggestion: Don't Change Tabs When Saving

### ISSUE THREAD

**Issue by StormFX** [goatfungus/NMSSaveEditor#116]
The title pretty much covers it. I don't know if there's a limitation with the editor that forces this behavior, but it changing to the "Main" tab when you save can be pretty annoying (farming seeds). :p

**Comment by goatfungus** [comment]
Currently when the editor saves a file it has to reload the files list as it will have changed due to the extra backup added. Then it reloads the save file from the top of the files list, and this in turn causes the tabs to be reset.

I agree that part of this step is unnecessary (reloading the file itself), and is basically just extra work the editor has to do for no reason. I'll look at tweaking this in the next update.

**Comment by StormFX** [comment]
If that functionality serves a purpose, I don't see a problem with it. But it would seem to be more intuitive if it was done in the background or at least, switches back to the previously active tab. :)

**Comment by goatfungus** [comment]
It didn't really serve a purpose, so I have stopped the editor from doing the reload in version 1.5.23.

**Comment by StormFX** [comment]
Awesome. Thanks! :)
