### ISSUE TITLE
One remaining Error Message (D6b) with the latest Editor Update

### ISSUE THREAD

**Issue by Goose7** [goatfungus/NMSSaveEditor#126]
I was getting this on what is now the latest Public release, and also with the latest EXP build that came out less than a half hour ago.  This is the only remaining "Not Found" for me.

Mem Usage: 515/3818 MB
Latest version: "1.5.24"
Current version: "1.5.24"
Loading saves for Slot 1...
Reading save file...
  Path: C:\Users\golde\AppData\Roaming\HelloGames\NMS\st_76561198299574875
  Slot: Slot 1 - NORMAL
  Filename: save2.hg
Parsing JSON...
  using name mappings: 24/08 experimental
  **name mapping not found: D6b**
Finished.

**Comment by ymgenesis** [comment]
I get the same:
![capture](https://user-images.githubusercontent.com/25252829/44935751-f7fe8e80-ad3f-11e8-96e9-027657043f27.PNG)
I never was using the experimental branch. Just updated to 1.58 when it was pushed out yesterday.

**Comment by goatfungus** [comment]
The label on the mapping file is "24/08 experimental", it doesn't mean you are using an experimental branch. It just means I haven't updated the label since it the experimental branch was pushed to public, and it makes absolutely no difference to the editor.

As for the other issue with exosuit technology, I am waiting until HG confirms either way whether restrictions for inventory containers will be hard-coded in the game. At present, they have only done it for one type of inventory, and I think that was an error on their part. For now, don't expand your exosuit technology inventory, just leave it at 7x2.

**Comment by Goose7** [comment]
@ymgenesis -- Don't worry. It has no impact on your save file.  We have been seeing these since the first 1.58 Experimental build a week ago.  GF has eliminated all of them but this one, which was introduced in the Exp that today became the Public release.

**Comment by goatfungus** [comment]
@ymgenesis The latest release of the editor, version 1.5.25, should now show "using name mappings: NMS 1.58" when you run it instead of "24/08 experimental". Should save a bit of confusion.

**Comment by ymgenesis** [comment]
Thanks guys!

**Comment by goatfungus** [comment]
Found the mapping at last! Released in new version.
