### ISSUE TITLE
Request: Zip File

### ISSUE THREAD

**Issue by StormFX** [goatfungus/NMSSaveEditor#132]
I'm sure I'm not alone when I say I'd prefer a standard zip file over a self-extracting archive. The reason: I can "explore" a zip file and drag/drop files like it was a folder. With an EXE, I have to extract the files before I can move them where I want them. Not to mention that doesn't play well with Windows UA.

**Comment by goatfungus** [comment]
The editor won't run properly from a zip folder, which is why the change. Too many people were reporting that the editor "doesn't work" because they were not copying the files out of the zip file, even through the install instructions clearly stated this.

Anyway, the self-extracting archive only contains 4 files, all of which should be extracted to the same place, so I'm not sure why anyone would want to drag/drop them to different places. Just extract it all where you want it and you're good to go.

Lastly, you only need to do this once. If you run the editor from one of the .bat files it will auto-update from then on out, so you don't need to manually download each time.

**Comment by StormFX** [comment]
The reason I drag/drop is because I have my directories set up a certain way. I download it, open the zip, drag the files into my working directory and then drag the archive into another folder and overwrite the old one so I always have the latest version.

That said, I wasn't aware that bat files would auto-update as I've always run the .jar file directly. But if you've got the files in place to auto-update already, couldn't you have the program do the update when it starts up?

As I said, running the exe directly causes Windows to throw up a UA window that requires you to force-run it. As far as the people complaining about a zip file, you'd think people would know how zip files work. $CurrentYear and all. :p

**Comment by goatfungus** [comment]
The reason I have the console showing is to provide background information... it is not meant to be closed. It also helps others with general Java errors that may not be picked up in the log.

The editor already checks for updates when it starts up and shows a confirm dialog. If you click the "Yes" button to upgrade, it will auto-download the new version, and restart the editor with the console. Pretty simple process.

So in the end, there is no reason to have to run the self-extracting exe more than once.

**Comment by goatfungus** [comment]
One more thing: The editor can't physically change it's own code on the fly, as that would be a major security risk. So the only real way to do this is via the console unfortunately.

**Comment by StormFX** [comment]
Fair enough. Thanks for the explanation. :)
