### ISSUE TITLE
Restoring a backup deletes the OTHER manual/auto save file [bug or feature?]

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#146]
Opening a previous backup, making a change, then saving it deletes the OTHER save - manual or auto, the one NOT being edited - in the active slot... Meaning, if I restore a manual save (save2.hg) then the auto save file (save.hg) is deleted.
Is this intentional? (if so, the logic here is a bit odd to my mind)

**Comment by goatfungus** [comment]
If you restore an older save from backup, the editor does the following:
- It will first backup both of your current saves
- Then it deletes the save files
- Then it creates a new save file based on the restored data

This is intentional, as it would be rather confusing if you switch between your new save to the other in-game, as they will be way out of sync time wise. I opted to clear them both out to save issues.
