### ISSUE TITLE
[BUG] Identical tech upgrades with same procedural number get deleted when dragged on top of each other

### ISSUE THREAD

**Issue by roie-r** [goatfungus/NMSSaveEditor#157]
What the title said :: When dragging a tech upgrade on top of an identical item - same ID and procedural number - one of the two is deleted. It's a minor bug, but still.  Cheers :)

**Comment by goatfungus** [comment]
The issue is when you add a module item using the editor, it has a stack size of 5. This is because the game data files define it as 5, but there is a hidden hard-coded rule in the game itself overriding it's own stack sizing for modules (setting them to 1). In your case, the module items you have added would be able to stack but are still only treated as one item in the game itself, so it would look like they are getting removed.

This is an example of an internal game bug which nobody would normally notice through natural gameplay, but are brought to light by external tools like the editor. I've found a ton of them already, which I've had to try my best to avoid wherever possible.

Anyway, I really would prefer not to hard-code any specific rules in the editor to fix this sort of game bug, and instead continue to rely on the game's own data files. So I think I will leave this one up to the end user for now.
