### ISSUE TITLE
Question about community research tier items

### ISSUE THREAD

**Issue by lofblad** [goatfungus/NMSSaveEditor#171]
Question: Is it possible for NMSSE to include the items that are released in the future tiers of the community research. I mean, are those files already in the game, and NMSSE can just unlock them in a future update?

**Comment by goatfungus** [comment]
Sorry for the delay in reply, it's been a busy few months for me.

The items database in the editor has to be regenerated after every release of the game in order to pick up what has been added. It was last updated for version 1.77, but there were a few extraction problems at the time and not every icon was extracted. I will look to regenerate this shortly after the next release and see if HG fixed the issues in the game files.
