### ISSUE TITLE
Feature Request: Realtime Inventory/Attribute Updating

### ISSUE THREAD

**Issue by ymgenesis** [goatfungus/NMSSaveEditor#172]
This is probably far out, but it would be amazing to have the save editor running while the game is open (which I currently do), load the save, edit some inventory values through the GUI, save (or not), and have the values update in the game realtime without the need to reload your save.

I understand this is more runtime code editing, rather than save file reading. Is the save file read constantly during runtime? Or once at load and written once at save? 

I've looked into trainers, cheat engine, etc., was just wondering if this awesome tool had the capability to alter those kinds of values in realtime.

Anyways, thanks for the great work you do!

**Comment by goatfungus** [comment]
Not possible sorry. The game doesn't use the save file as a runtime state of the game (ie: memory) it uses it as a snapshot at a point in time so that it can restore when needed. It has no need to continually check the save file after it is initially loaded.

Trainers and tools like Cheat Engine work by hacking into the memory the game is using while it is in use, which can be pretty risky and also very complicated, as you'd have to work out exactly which memory addresses are being used for what. This is why most tools like that are fairly limited in what they can do.
