### ISSUE TITLE
bug: Save editor cannot find .bat files in folder from ps4 save

### ISSUE THREAD

**Issue by aCertainPerson** [goatfungus/NMSSaveEditor#176]
hello the editor isnt able to show these files, when i enter the folder it comes up as blank

**Comment by goatfungus** [comment]
The save editor doesn't look for .bat files at all, as save files have an .hg extension.

If your save files don't have a .hg extension, then they are probably in a completely different format that the editor won't be able to read, and since I don't have a ps4 there's not much I can do to help, sorry.
