### ISSUE TITLE
Landing Pad

### ISSUE THREAD

**Issue by harrija0** [goatfungus/NMSSaveEditor#179]
My Artimis quest glitched.  Is there any way to gain the landing pad from this trainer?

**Comment by Entoarox** [comment]
You can fix the quest as such:
- Go into the JSON editor
- Open the `PlayerStateData` node
- Open the `MissionProgress` node
- Search through this list, from the bottom, for a quest with the name `ACT1_STEP##` (`##` differs depending on your current mission in the chain, hence starting from the bottom, since you'll find the last mission in the chain first that way)
- Where it says `"Progress":#,` (`#` being a number) increment this number, then save.

This process will "skip" the step that got bugged, making the game believe it was completed.
