### ISSUE TITLE
Base Info (backup/restore/move) missing

### ISSUE THREAD

**Issue by JellyPeixe** [goatfungus/NMSSaveEditor#184]
Hi, im trying to move my base but I cant select my existing bases on the base info tab. The backup, restore an move base computer buttons are grayed out too. Is this a bug or am I doing something wrong?
![ScreenNMS](https://user-images.githubusercontent.com/54193604/63204633-1dc79500-c070-11e9-803a-a7f8111523f6.png)

**Comment by goatfungus** [comment]
It may be something to do with the BEYOND update.... I haven't tested everything yet as it's a lot to go through.

**Comment by Alterios** [comment]
It looks like there are 4 strings that it can not read. 3 are related to bases and 1 seems to be related to trade. I looked at a save file that I have that I haven't opened since the update and those strings don't seem to be in that one. They look like new entries, possibly created when it converts an old save to the new format.
![errors](https://user-images.githubusercontent.com/2030690/63211447-2c8c6700-c0c5-11e9-8d1e-245813241249.JPG)

**Comment by Yolo56** [comment]
It's not because of that. I search a little and found  where we can change that. 
First you need to go in the Advanced Edit Save.
![image](https://user-images.githubusercontent.com/54182465/63306939-e44f8d80-c2ec-11e9-9a0c-9e672d5227b2.png)
You click here
![image](https://user-images.githubusercontent.com/54182465/63306975-ffba9880-c2ec-11e9-8f5c-50d8f11aa46e.png)
And the location of your base are there.

**Comment by JellyPeixe** [comment]
> It's not because of that. I search a little and found where we can change that.
> First you need to go in the Advanced Edit Save.
> ![image](https://user-images.githubusercontent.com/54182465/63306939-e44f8d80-c2ec-11e9-9a0c-9e672d5227b2.png)
> You click here
> ![image](https://user-images.githubusercontent.com/54182465/63306975-ffba9880-c2ec-11e9-8f5c-50d8f11aa46e.png)
> And the location of your base are here.
> ![image](https://user-images.githubusercontent.com/54182465/63307064-46a88e00-c2ed-11e9-8a1f-a57afa7275fb.png)
> After that, you search the name your base with CTRL + F
> And you just above that, you will see
> ![image](https://user-images.githubusercontent.com/54182465/63310692-f4bb3480-c2fb-11e9-869d-08dad2b78d1c.png)
> 
> **BUT be carefull, all the building of your base, will move compared to the location of your base computer. So dont forget to do a back up before doing anything.**
> 
> The number you can see below persistentPlayerBases, are all the bases you made.
> With all the building location values, and you will to change them too.
> So be ready, to change all the values, of all the building.
> 
> And to do a lot of test, to figure how the building move compared to the computer base.
> and if you get how building location move, compare to the initial location value of the base. Be nice and share your tests.

Thank you, I'll try this method. I mentioned the base info button because I used to use it in older updates in order to quickly move my base, but it seems i'll need to wait for a new version of the inventory editor... I don't feel good messing with those numbers and locations, I think I would mess everything up. But thank you anyways :)
