### ISSUE TITLE
New inventory location?

### ISSUE THREAD

**Issue by temp-999** [goatfungus/NMSSaveEditor#187]
Beyond added a new inventory location. It might be nice to be able resize and restock it?

		"CookingIngredientsInventory":{
			"Slots":[

**Comment by goatfungus** [comment]
Agreed.
I will have a look at this as I get time.

**Comment by uecasm** [comment]
While on the subject, it'd be nice to have a view for the `ChestMagicInventory`, which is the Base Salvage Capsule.  (Especially since it appears to be bugged in-game at the moment.)

There's also a `ChestMagic2Inventory` but I'm not entirely sure what it is, whether it's some other inventory I haven't noticed or if it's just additional slots for the base capsule.

**Comment by temp-999** [comment]
> Agreed.
> I will have a look at this as I get time.

Thank you very much! Refills just fine! 

Not sure about uecasm's comment but #187 can be closed as far as I'm concerned.
