### ISSUE TITLE
Resize Technology for Exosuit

### ISSUE THREAD

**Issue by JimHart64** [goatfungus/NMSSaveEditor#203]
When I attempt to resize the Technology slots for my exosuit it reverts any numbers entered back to the original numbers when I click save. Is this unchangeable, is there a a flaw in the save editor, or am I doing something wrong?

**Comment by goatfungus** [comment]
8x6 is the highest it will go.... the game won't allow any higher.

**Comment by JimHart64** [comment]
Thank you for the clarification. It might be a good idea to gray out the option to adjust inventory size for inventory values that are unchangeable as it can cause confusion.

**Comment by ZerotheReploid** [comment]
I've still got 7x3 technology inventories from a few versions ago. Really not jazzed about the slots being so limited, given how many materials ans upgrades you have to carry on you at all times if you want to be able to do everything.
Is there no way to override these new restrictions?

**Comment by Entoarox** [comment]
@ZerotheReploid The game forces the exosuit tech inventory to 7x2 in size, even if it is bigger - if you really have a bigger exosuit tech inventory on one of your saves that remains in beyond, you should share that save, it might expose whatever flag goat needs to set in order to allow a bigger then 7x2 tech inventory on the exosuit.

**Comment by Mojodishu** [comment]
Been trying and trying to alter this aswell for my survival playthrough. every change got reverted back to 7x2. 
Was going for a 7x3. Glad its not just me then. Really hope this will be something we can do in the future aswell.

**Comment by ZerotheReploid** [comment]
Wait, does it matter which inventory it's from? My 7x3 is on my ship, but back when I made it, 7x2 for the exosuit was enough.

**Comment by Entoarox** [comment]
Ships are able to go up to 7x3 yes - but the exosuit can only go to 7x2

And with the sheer amount of new items added in beyond, inventory space is even more valuable then before (Even on normal, where you no longer need to deal with most of the stack limits!)

So the 7x2 tech limit on the exosuit is a even bigger issue because we can no longer afford to use general inventory space for our tech, we need it for all the new items....

**Comment by Mojodishu** [comment]
aye not sure if they are worth a spot, but the passive resistance's that give you 21% resist and does'nt need to be charged would be awesome if they affected the active one next to it so it last long.
But that would mean 4 passive, 4 active, normal hazard and the extended battery= 10 slots just for the hazard protection.
Then you got your jetpack and life support aswell
7x2 is quickly filled indeed. thats why i wanted a 7x3 instead :(

**Comment by Entoarox** [comment]
Personally, I just would like them to remove the hard-coded size limits altogether, if we want to mod our inventories to be 8x6 all over, then let us! 😕

**Comment by Entoarox** [comment]
Btw, @goatfungus The 7x3 limit on ship tech inventory is not needed (anymore?), I used manual JSON editing to make the inv 8x6, and the game just does not care, unlike with exosuit tech where it forces the inv back to 7x2

**Comment by ZerotheReploid** [comment]
@goatfungus Where exactly do you go to manually change your ship tech inventory? The save format is really dense and difficult to navigate

**Comment by Entoarox** [comment]
In the JSON editor, go down: `PlayerStateData`, `ShipOwnership` then find the array entry that matches the ship you wish to edit (Custom ship name will help a lot with that) and go into `Inventory_TechOnly`
There edit the `Width` value to be 1~8 inclusive, and the `Height` value to be 1~6 inclusive.

Save when asked to, and the editor will display the resized ship inventory, allowing you to make any further changes in what slots are unlocked there.

(Doing this process wont work for the exosuit tech inv, because the game will force-resize it back to 7x2 when you load the save)

**Comment by goatfungus** [comment]
This resize problem has been fixed now.
