### ISSUE TITLE
No source code?

### ISSUE THREAD

**Issue by SonicProgramming** [goatfungus/NMSSaveEditor#210]
What's the point of using github if you don't provide the source code?
Being a Java programmer myself i'm always looking for an opportunity to read others' code to improve my skills.
You could also benefit from this because other people would have probably noticed something worth an enhancement in your code, and people DO improve FOSS, just look at any example. There are thousands of contributors and thousands of open-source projects that are still alive and are still improving thanks to the community.

So please, either show your code, or don't use github.

**Comment by goatfungus** [comment]
Just because GitHub is commonly used for open source projects and to share source code does not mean that is the rule. In fact, GitHub itself has private repositories and allows collaborators to use the public issue tracker at the same time, which is what I have done.

I chose to host on GitHub for convenience mostly, and have welcomed help from others in the past. However, when you publicly declare an ultimatum (effectively telling me to show the code or discontinue the project), it surprisingly doesn't make me feel like I would even want your help.

Please be a bit more constructive in future.
