### ISSUE TITLE
Pictures and more

### ISSUE THREAD

**Issue by Windgott1910** [goatfungus/NMSSaveEditor#333]
Could you add pictures of your ship? so when you change the seed of it you can see the new ship.
And, could you add that you can see the stats of upgrades?

**Comment by ukmerlin** [comment]
The application only reads the save file. The seeds are buried in the game code. Best bet is to look thru the seed exchange to find what you want, or experiment with close seeds. For the upgrades not sure of the exact question but if upgrade modules are bought they do not reveal themselves until installation time since they are procedurally generated based on what you already have.
