### ISSUE TITLE
Expeditions update?

### ISSUE THREAD

**Issue by RaddaTatTat** [goatfungus/NMSSaveEditor#366]
Have you started work on the expeditions update?

**Comment by JB2021-81** [comment]
Goatfungus,

I'd LOVE an update for Expeditions, they Literally force me to surrender a Maxed out weapon for a starter peashooter after completing Phase 2... They did not have an option for add to arsenal or anything.. That is why I'd love for there to be a save game editor for this new stuff, I want to Max out weapon stats, and anything else to give me some sort of edge but not too crazy. I do want to enjoy the expedition then HG does this bull. Just amazing. 

I would like to edit inventories too, they seem to top out at 24 for weapons, I'm sure I had my base game at 48 slots for main inventories..

While I'd love this save editor updated asap, I do understand if you have a ton to pour over, it was a massive update, took a trainer maker I know 8 hours to make a solid trainer the first day the new update dropped. That trainer is good, but is limited, that's where your editor comes in, been a fan for 5 years, but this recent updated forced me to create an account to comment.

**Comment by theonetobe24** [comment]
the comment by JB literally made me set up an account just to say i agree i was all maxed out on my ps4 and when i got my pc i i dint want to grind another 400 hours to get to the same level. thanks to this save editor i had fun once again. since the new update got released i haven't even bothered playing, re-grinding. in real life i have business to worry about so I don't have the time. i would literally pay for this product

**Comment by goatfungus** [comment]
Version 1.7.4 (just released) should support Expeditions update. Enjoy
