### ISSUE TITLE
Does this editor support MS saves?

### ISSUE THREAD

**Issue by DS-Karma** [goatfungus/NMSSaveEditor#419]
I tried to open the folder including all like 10 folders holding my save data and nothing... i know nomnom works.

**Comment by goatfungus** [comment]
Can you send me a copy of your save file data?
Currently the editor is designed for the Steam save location, but MS might be different.

**Comment by Mike-Blackwell** [comment]
I believe the XBox PC save file is; C:\Users\usernamel\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\RANDOM LONG NUMBER\ANOTHER LONG NUMBER (saved files are the larger files (which requires one to look at the timestamp to figure out which is the latest, the other two aren't used within each folder)

**Comment by goatfungus** [comment]
I just need to be able to see the layout of all the directories/files to make the editor understand them. There will be a reason for the random numbers, perhaps a key or something.

**Comment by yashjahit** [comment]
Hello there,

As @Mike-Blackwell  said, the saves are located there. 

I have attached one of my saves, the long name is the second "ANOTHER LONG NUMBER" from Mike's answer. If you need anything else, feel free to ask


[Save File.zip](https://github.com/goatfungus/NMSSaveEditor/files/7130734/Save.File.zip)

**Comment by SirCathal** [comment]
@goatfungus Here are my save File too, because I really want that Feature :-)
I made a Feature Request for 2 Features https://github.com/goatfungus/NMSSaveEditor/issues/444 one of them is the MS Store Save format.
The ZIP includes the complete Save Folder. the wgs Flder is inside the Folder:
c:\Users\<windowsUserName>\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\
I Think WGS is for Windows Game System and inside the long number 00090000074A00FC_29070100B936489ABCE8B9AF3980429C is the Identifier for NMS.
[wgs.zip](https://github.com/goatfungus/NMSSaveEditor/files/7149405/wgs.zip)

If you want to test by yourself, NMS (PC&Xbox) is included in the Microsoft Game Pass  Ultimate. That is Available for 1€ in the first month and It can bee directly cancled after paying the 1€

But I would be happy to help you testing.

**Comment by goatfungus** [comment]
MS Store Save Format is coming soon, just need to spend more time testing it.

See [here](https://github.com/goatfungus/NMSSaveEditor/issues/444#issuecomment-919928259) for details.
