### ISSUE TITLE
No Published Releases

### ISSUE THREAD

**Issue by Valastiri** [goatfungus/NMSSaveEditor#432]
Although any git-savvy user would understand how to get the relevant files OR simply clone/fork this repo a release would be nice. 

Would make it easier to see your CHANGELOG.md.

**Comment by Valastiri** [comment]
Heh forgot to link remote before PR.

**Comment by goatfungus** [comment]
The batch file, included in the archive EXE, contains some basic automatic-update functionality. If you run the editor from the batch file rather than the jar directly, then you will no longer need to download the zip file manually from GitHub.

This feature has been in place since I first released the editor to the public, but I have noticed recently that a lot of people are choosing to clone the project each time, or download it all as a zip and overwrite their local install, when they don't really need to.

**Comment by Valastiri** [comment]
Feel free to close this issue and subsequent PR. I actually did not know the batchfile provided said function as I too just cloned the repo locally. 

Would be nice to have it documented on your README.md as either part of the installation or as a recorded feature. Just gave it a try with v1.8.3 and works flawlessly.
