### ISSUE TITLE
Error parsing JSON: invalid switch: b ?

### ISSUE THREAD

**Issue by criscrosaplesos** [goatfungus/NMSSaveEditor#495]
All of my saves work just fine but one, my main one of course. I'm very new to all of this so haven't tried anything yet to fix this
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/7652759/NMSSaveEditor.log)
.

**Comment by Devilin-Pixy** [comment]
Every game slot usually has a manual and auto save. Your Slot 1 which appears to error, possibly due to save corruption, is trying to load the manual save. Have you tried loading the slot 1 auto save instead? Both are from Dec 3rd 2021 with not much of a difference in playtime, so if the auto save does work, you will likely not lose much with using it instead.

**Comment by criscrosaplesos** [comment]
Yes, Ive tried both, neither seem to work at all.

**Comment by goatfungus** [comment]
This should be fixed in later version. Cleaning up
