### ISSUE TITLE
Planet edit features request

### ISSUE THREAD

**Issue by roadapathy** [goatfungus/NMSSaveEditor#497]
I'm so sorry, I didn't see a place for this so this isn't a "new issue." The editor works GREAT!

Are there any ways to edit planets that have not been uploaded to the server? Like turning a barren planet to lush sort of thing.

**Comment by xaminmo** [comment]
This isn't really possible.  Planet seeds are not stored locally.  The only mods that are local are when you modify terrain within the area of your base.

This is why sometimes you modify a planet in-game, and wander off, come back (if you can) and it has reverted.  Or, it reverts when you're working on it, and you drop through a hole.  Or, you're in multiplayer, but not paired up with your friend properly, so they see different terrain than you do because one of you modified something in a save, or similar.

**Comment by xaminmo** [comment]
Planets have just a single seed.  If you find a seed you like, you might copy that in the JSON editor.

**Comment by goatfungus** [comment]
Nope.
