### ISSUE TITLE
entering hex value in coordinate viewer can yield invalid galactic coordinates

### ISSUE THREAD

**Issue by cerdish** [goatfungus/NMSSaveEditor#552]
when using the coordinate viewer it looks like the coordinates don't roll over to negative numbers when converting from hex coordinates. y values over 128 should circle back to -128 and values on z and x roll over at 2048 i think. so if the hex value for x is 2049 that would actually be -2048 when translated.

https://nomanssky.fandom.com/wiki/Portal_address

the hex address:

020EF35CAC62

the incorrect result:
"GalacticAddress":{
	"VoxelX":3170,
	"VoxelY":243,
	"VoxelZ":1482,
	"SolarSystemIndex":526,
	"PlanetIndex":0
}

i believe the values 243 and 3170 are incorrect.

**Comment by Devilin-Pixy** [comment]
The Portal Code does get correctly translated to Galactic Coordinates.
This means breaking apart the values, then applying shifts, because Portal Code is translated to have the Core at 0, 0, 0, while the Galactic Coordinates does not have the Core at 0, 0, 0.

Portal Code: 020EF35CAC62
0 = planet, 20E = Solar System Index, F3 = Y, 5CA = Z, C62 = X

Translates and shifts correctly to

Galactic Coordinates: 0461:0072:0DC9:020E
0461 = X, 0072 = Y, 0DC9 = Z, 0 = Planet, 20E = Solar System Index

The problem is the conversion from the hex code of the Galactic Coordinates, to decimal values used in the Save Data, after doing a Portal Code search.
A shift needs to be applied to make the core of a galaxy be at 0, 0, 0.
This shift in your example is not applied.

For X and Z this shift would be -2047 (dec), while the shift for Y = -127 (dec), AFTER conversion.

X = 0461 (hex) = 1121 (dec) - 2047 (dec) = -926 (dec) <--- No match with Save Data
Y = 0072 (hex) = 114 (dec) - 127 (dec) = -13 (dec) <--- No match with Save Data
Z = 0DC9 (hex) = 3529 (dec) - 2047 (dec) = 1482 (dec) <--- Matches Save Data

So your conclusion is correct, the X and Y values are wrong, they have not been shifted like they should.

**NOTE**: This only happens when using Portal Coordinates to search for in the Coordinate Viewer.
If you use Galactic Coordinates as a search, the shift does get applied correctly, and the result is perfectly fine.
