### ISSUE TITLE
WARNING: name mapping not found: =bJ

### ISSUE THREAD

**Issue by themunchkinman** [goatfungus/NMSSaveEditor#565]
Please forgive if this is not an issue. Wasn't sure if there was a general submission/discussion space.
First time encountering this specific mapping not found.
Is it generally safe to continue editing/saving? Trying to fix something that glitched.

`WARNING: name mapping not found: =bJ`

**Comment by Devilin-Pixy** [comment]
This is in most cases not an issue. It just means there is a new mapping found which has not been translated to something we can easily read. It will instead continue to use the internal naming and continue to function fine.

`=bJ` will with a future update be given a meaningful name ("TraitsSeed")

**Comment by themunchkinman** [comment]
So at worst, it will be completely ignored by the editor.  

(I'm pretty confident the developer plays the game, so likely doesn't need much from us as far as identifying discrepancies.)

**Comment by Devilin-Pixy** [comment]
> So at worst, it will be completely ignored by the editor.

No, it's not ignored, just not given a fancy name we can easily understand

**Comment by rasa2k** [comment]
Good to know. I also had a glitched savegame where I was stuck in the roof of a space station and could not get out. The "Coordinate Viewer" warp saved my ass and a 400 hour savegame. Thanks for that! I was afraid that somehow my savegame were still corrupt due to these warnings of "name mapping not found". But that sounds like not to be the case. :) Happy gaming!
