### ISSUE TITLE
MULTITOOL NOT CHANGING

### ISSUE THREAD

**Issue by AlaskanGrizzz** [goatfungus/NMSSaveEditor#597]
All changes to multitool do not transfer over to live gameplay. Automatically reverts to original configuration after reload.

**Comment by h8rt3rmin8r** [comment]
I am having the same issue.

Ever since (roughly) the [Leviathan 3.92](https://www.nomanssky.com/2022/06/leviathan-patch-3-92/) patch, the NMSSaveEditor has been unable to make changes to multitool(s). Upon loading into the game, a placeholder multitool appeared in the inventory but that placeholder was unusable. All previously owned multitools were missing entirely. The only way to recover multitool usage in the game is to buy a new tool from an NPC.

**Comment by h8rt3rmin8r** [comment]
Please update soon - NMSSaveEditor is basically unusable currently and I'd love to roll some save edits before the Leviathan event concludes.
