### ISSUE TITLE
Upgrades lost after loading edited save.

### ISSUE THREAD

**Issue by Bigtuna00** [goatfungus/NMSSaveEditor#6]
I added some suit, ship, and multi-tool upgrades in game. They seem to load up ok in the save editor but after making changes in the editor, saving, and loading that game the upgrades are lost.

It does not affect *all* upgrades. Seems to affect suit upgrades the most, especially Life Support and Movement.

I can provide save files if that helps.

**Comment by Bigtuna00** [comment]
Steps you can try:

* Add an S class Movement Upgrade module in the editor.
* Load the game, apply the upgrade, save.
* Load the save in the editor, make some changes (e.g. add an item to inventory).
* Save the changes, load the save game.

In my case the Movement upgrade will be gone.

**Comment by FlawedOne** [comment]
I can verify this also. Although in my experience it affects quite a lot of exosuit upgrades.
My radiaton, heat, cold, and toxicity never got reset. Although those are in my Technology slots.
Underwater, movement, life support, and shield constantly got reset after. I didnt do them in one go, and the older upgrade modules always got deleted when i put thr new consumables in the inventory. Only way to circumvent was to put everything in at once. Havent tried to modify exosuit inventory since, so i dont know if that will delete the upgrades.

**Comment by FlawedOne** [comment]
Also this does not seem to affect multitool and ship inventory. Nor l, like i mentioned, the exosuit technology slots. Seems like its only the main exosuit inventory.

**Comment by FlawedOne** [comment]
Im using an older save from Atlas Rises.

**Comment by krgii** [comment]
I'm using my save from 1.0. Since editing my save, no procedural technologies will save to my main exosuit inventory. After I exit the game and reload they all disappear. Exosuit technology, multitool, starship, exocraft, and freighter work as intended. Blueprint technologies work as intended too.

**Comment by Bigtuna00** [comment]
Looks like the 1.51 patch *may* address this:

> Fixed an issue where upgrade modules installed in the main Exosuit inventory would not be saved correctly.

https://www.nomanssky.com/2018/07/next-patch-1-51/

**Comment by krgii** [comment]
Seems to be working for me since update.

**Comment by goatfungus** [comment]
NMS Patch 1.51 has fixed this, as it was a problem with their load process.
