### ISSUE TITLE
Account tab greyed out

### ISSUE THREAD

**Issue by ChitoBurrito** [goatfungus/NMSSaveEditor#664]
Not sure if on purpose due to new update or something else.
![account](https://user-images.githubusercontent.com/7956412/194778378-b8e2ff42-c39b-45ce-b1e7-c2271e3c580b.PNG)

**Comment by goatfungus** [comment]
Can you please send me a copy of your log file? NMSSaveEditor.log
You should be able to find it in the same folder as the editor.

**Comment by ChitoBurrito** [comment]
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/9745986/NMSSaveEditor.log)

**Comment by tanareed** [comment]
I'm seeing the same thing here.

[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/9749178/NMSSaveEditor.log)

**Comment by goatfungus** [comment]
It turns out that HG's "JSON" format no longer complies with the standard since the update. I noticed this on some saves as well. I am wondering if they will fix this issue in the coming days, or whether I need to break the standards as well. I'm just concerned that if I make a change on my end it will break things.

**Comment by goatfungus** [comment]
Update 1.11.2 should fix this problem now....

**Comment by ChitoBurrito** [comment]
Thank you, it worked! :)
