### ISSUE TITLE
garbled text

### ISSUE THREAD

**Issue by satotatsu5** [goatfungus/NMSSaveEditor#686]
Japanese name of Base Info is not displayed correctly in NMSSaveEditor Ver:1.11.2
It was displayed normally in Ver:1.10.7

**Comment by goatfungus** [comment]
A number of things were changed in the save format in the Waypoint update and I had to adjust the way save files are read in, but since all my files are in English I had no way to test it on other languages.

Can you please send me a copy of any save with Japanese text to: goatfungus@gmail.com
I'd really like to see what else has been changed in the format.

**Comment by satotatsu5** [comment]
sent a SAVE

**Comment by goatfungus** [comment]
Should be working now
