### ISSUE TITLE
Special characters not showing up correctly in JSON

### ISSUE THREAD

**Issue by Lenni009** [goatfungus/NMSSaveEditor#706]
Some special characters show up in a weird unicode form in the JSON. For example the German lower quotation mark `„` shows up as `\u00E2\u0080\u009E`.

**Comment by MGJerry** [comment]
Yeah, that's just ASCII encoding. Due to its limit of 256 characters (when using only 2 hexadecimal characters behind "\u00"), foreign characters and many other things are a combination of multiple characters.
Got this exact problem when using Chinese characters. A quick Google will give you a list of all possible combinations.

**Comment by Lenni009** [comment]
Just to be clear, there are no cases where all 4 hex characters are filled for these \u characters? It is always \00?

**Comment by MGJerry** [comment]
From what I've seen so far, the editor only translate special characters to unicode characters that use the last 2 hex code, never all 4 of them.
This is either happening due to me not playing the game enough or because of how the editor (maybe NMS itself) saves special characters.

**Comment by Devilin-Pixy** [comment]
This is the way these characters are stored for unicode characters outside the range for your native/installed language. We will not see them correctly in-game unless you have the language installed and active with your Operating system. Not sure if this would then also make them visible in the editor, but I doubt it

**Comment by MGJerry** [comment]
Yeah, I had Japanese installed ('cause class from uni), input some in my pet's name and base's name (also settlement too). They all turned into groups of unicode character with \u00** (except 一, somehow normal?)

**Comment by goatfungus** [comment]
I know this is a bit delayed, but there have been changes to the way NMS stores values in the save file. Even in my saves which are entirely English, I still get weird unicode character marks all through the file. I have tried to reproduce that in the editor as much as possible so that the game can actually read the saves once they have been modified.

**Comment by Lenni009** [comment]
The [NomNom](https://github.com/zencq/NomNom) save editor can process these characters without issues
