### ISSUE TITLE
Feature Request: Source Code

### ISSUE THREAD

**Issue by Starkiller4011** [goatfungus/NMSSaveEditor#71]
Would be nice to have the source code to peruse and/or contribute to, kinda what GitHub was designed for, open source projects...

**Comment by goatfungus** [comment]
See #49... maybe someday, but for now it is as it is. Is there something specific you are looking for?

**Comment by leobartkus** [comment]
I don't know about @Starkiller4011 , but I would honestly rather port this to another language than install the JRE.

**Comment by radistmorse** [comment]
A bit late to the party, but in my opinion, being open-source is the default for this kind of project. People expect it to be open unless there is a reason. Like, "I have 30mb worth of pngs that are HelloGames' intellectual property and I don't want to host them in the open". Because when there is no apparent reason, people start to suspect something sinister, especially since you've taken some extra steps to obfuscate your code. That's why, I think, there is so much hostility in the requests. There are many good reasons to make the project open-source. Technical and organizational. What if your hdd dies or you get under a bus. Also, bundling other people's IP in your project is a bad idea regardless of whether it's binary or not.
