### ISSUE TITLE
Problems with 1.11.3

### ISSUE THREAD

**Issue by darkangle0512** [goatfungus/NMSSaveEditor#716]
I'm using 1.11.3 for now and have some problems:
1/ I loaded game with old save, move all tech to technology storage then save and load by this, still have warning message that name mapping not found.
2/ I see that capacity of storages now seem not right. From wiki each basic resource can be stack 9999 but only 1000 in save editor for now (not checked other item types), and if I move item between chest, it will become only 500 stack.

Please check and let me know if i was wrong. Thanks for great save editor anyway.

**Comment by unpococloco** [comment]
When I try to go rename one of my bases, the bases menu is empty

**Comment by BONEGUNN** [comment]
I'd be willing to pitch in some cash with others who are having the base save/export issue if it helps speed the process at all. I barely play without that function. I wouldn't play at all if not for the goat fungus save editor. All is very much appreciated.

**Comment by goatfungus** [comment]
All bases should be viewable now.

**Comment by BONEGUNN** [comment]
That is incredible! I haven’t been able to play the game for so long since most of what I do is build bases in isolation and then pop them up in strange places. I really appreciate your diligence. Do you have a Zell account? I would like to get together with the other folks that were having this problem and put together a token of our appreciation. Zoe is the only online transfer. I can use due to some company restrictions.Bryan Kane607-738-4334Confidentiality Notice:  This email, including any attachments, may be confidential, privileged or otherwise legally protected.  It is intended only for the addressee(s).  If you are not the intended recipient, you are prohibited from disseminating, copying or otherwise using this email or its attachments.  If you have received this email in error, please notify the sender immediately by reply email and delete the email from your system.On Apr 22, 2023, at 11:31 PM, Brendon Matthews (GoatFungus) ***@***.***> wrote:﻿
Closed #716 as completed.
