### ISSUE TITLE
Add source code

### ISSUE THREAD

**Issue by itpropro** [goatfungus/NMSSaveEditor#744]
Uploading binaries to GitHub in not in any way the purpose of this platform. Please remove the binaries or add them to releases and add the source code, so that the binaries are built and released to the releases (where they belong) and that users have the possibility to compile it from source themselves.
Open Source is about sharing knowledge, letting people contribute and learn from the source code.

**Comment by itpropro** [comment]
@goatfungus if you don't want people to compile from source themselves to generate trust, can you at least provide a signed, self contained binary and hashes for each release to have at least minimum possible trust?

**Comment by hax4dazy** [comment]
The "issue" is that they don't want to post the source code because they are still working on it. The problem with that is that we cannot now see what the program does or port it to something better like C#/C++/C/Python.

This also has the added bonus of when something does break it takes longer to repair then when it would actually be open source. Updates are currently only done by the dev and whenever they have time instead of whoever decides to fork the project and PR a fix. 

[This is the issue where in they said they don't want to release the source code](https://github.com/goatfungus/NMSSaveEditor/issues/49#issuecomment-410192106)
