### ISSUE TITLE
Bug: When exporting a Ship, the cargo is ignored

### ISSUE THREAD

**Issue by SirCathal** [goatfungus/NMSSaveEditor#752]
When I export a ship, all associated properties are exported.

Unfortunately, only the technical inventory is exported. 
The cargo inventory is completely ignored.

In the past this was possible.

It would be great if this would work again, because I like to specialize my ships and therefore their stock inventory usually contains everything necessary for its task. 
I use the export as a warehouse because the current 12 possible ships per save are not enough and I just want to collect more. 

But that doesn't work well anymore if the export is incomplete.

**Comment by goatfungus** [comment]
The ship inventory export function has always had a filter on items in the main inventory ensuring that only technology items are preserved. Since then, they added the Cargo container and I forgot to implement the filter on it in the editor (bug). In Fractal they removed the Cargo container again and renamed the main inventory "Cargo", so once again all the items will be filtered as originally intended.

My plan for this function has always been to export things that were part of the ship, not including cargo. I plan to update the freighter export function to do the same as well (it currently exports the base only).

So you use all 12 ships (previously only 6) and a swarm of backups to hold all the items you have collected because they won't fit in all the containers? Sounds like you should be featured on an episode of Hoarders! Lol. Anyway, I'll have a think about it, and maybe it would be possible to include a custom setting to allow you to export products and substances too. Just bear in mind that the highest priority with the export/import functions is to improve the freighter export first, and only then I can move onto other stuff.

**Comment by SirCathal** [comment]
A little check mark when exporting a ship so that all ship inventories would just be exported when checked would be great.

And yes, I am a collector. But I have also played several thousand hours of NMS and there are just so many great ships and then also in different colors :-) 

I hope Hello Games will introduce a ship hangar at some point. Then we could build a big hangar on a planet and choose the active ships there. 

If it's up to me that could be 100 or more :-)

Currently I have about 30 ships stored as export. 
I understand if it is not the highest priority, but if you think about it I am already happy.
As I said the export with cargo inventory has worked once

**Comment by goatfungus** [comment]
How about something like this?
![image](https://user-images.githubusercontent.com/41274031/230742554-32d4a4d5-c8a7-4e7d-a0c9-f6e0a61bef60.png)

**Comment by goatfungus** [comment]
I have implemented the export options (see above post) in the latest version, 1.12.0.

**Comment by SirCathal** [comment]
Thank you, it works fine for me.
There is only a super small Issue.
When you Import a Ship, the Load Button is called Save. 
The Import works, it's only the Button Lable
