### ISSUE TITLE
single exe / self-contained version

### ISSUE THREAD

**Issue by kgersen** [goatfungus/NMSSaveEditor#76]
To reach a wider audience, It would better to have a single exe file, containing the jre and optionally auto-updating itself. 
aka Self-Contained Application Packaging.

tbh, It's quite annoying and clearly outdated in 2018 to have to install (and update!) the JRE and download and unzip an archive...

**Comment by dark-1** [comment]
Any Examples of such types of App that you have come Across , Please?
I am trying to find some jar to exe which are Self-Contained Application.

Best regards 👍

**Comment by kgersen** [comment]
I don't use Java at all so can't help you there. 

https://docs.oracle.com/javase/tutorial/deployment/selfContainedApps/index.html may be ?

https://portableapps.com/ may be ?

**Comment by goatfungus** [comment]
I am currently building a windows c++ wrapper application for this which will include an auto-updater (see #44).

As for "clearly outdated", you do realize that in order to use newer .NET frameworks you have to do exactly the same thing? Admittedly most of the apps produced with .NET have the ability to auto update the framework itself, but as I said, I'm working on this.

For now though, you'll spend only a tiny fraction of the time i spend developing this editor doing a manual download from github, so I don't think you have much to complain about.

**Comment by goatfungus** [comment]
I'll close and redirect this one the #44 to keep it all together.
