### ISSUE TITLE
Bitdefender warning.

### ISSUE THREAD

**Issue by AlucardTheRed9** [goatfungus/NMSSaveEditor#774]
Trying to download the editor throws Bitdefender errors about multiple connection threats/infected pages. Oh, and the download gets locked. I dont know thats a false positive, or not, but I reported it none the less. If the authorities in this site have the power to evaluate such files, they better do. Better be safe than sorry.

**Comment by goatfungus** [comment]
It's a false positive, sorry. I'm not sure how to get around the issue, but there are no security risks in this app.

**Comment by AlucardTheRed9** [comment]
Maybe not in the app. The problem is that the place from wherever im trying to download it, is flagged as an infected page.

https://raw.githubusercontent.com/goatfungus/NMSSaveEditor/master/NMSSaveEditor.exe

Idk what it is, but something about address is making it being flagged by Bitdefender. And while im aware that every antivirus can throw false-positives, I trust Bitdefender more than some random page. Perhaps there is simply an issue in how the exe is being downloaded from the address? Or maybe in the way that the exe is compiled or is set to function?

I managed to download it in a separate, more isolated space, and scan it with Bitdefender, and I find it odd, that after scanning the .exe or the extracted editor files, I get over 3000 results the first time. but after trying to scan them again, I get either 1 (from the zip .exe) or around 9-10 (from the editor files) results. While none of it was flagged as malicious, its as if whatever else that was scanned within those files simply vanished. In the current age of various technological advancements, I would not be surprised if people used some sort of mind-fuckery methods for malicious purposes.

But in any case, if there is truly no risk in this program, then Im sorry for lashing out. Im pretty direct.

**Comment by AlucardTheRed9** [comment]
I decided to take a leap of faith

**Comment by leeterry** [comment]
I scanned the files with Virustotal (uses multiple scanners) and Malwarebytes (the same as I do every download). Malwarebytes said it was clear and the only 2 detections it found on virus total were false positives (even bit defender said clear on Virustotal). The fact that only 2 out of 72 scans found anything says everything.
[https://www.virustotal.com/gui/file/d3ee33d9791711faf38faeac500046d68cdfde12368cc9762d085a8dd6d8b283](https://www.virustotal.com/gui/file/d3ee33d9791711faf38faeac500046d68cdfde12368cc9762d085a8dd6d8b283)
Furthermore, after I extracted the editor, I added it to a rar file and did another scan which found nothing. 
[https://www.virustotal.com/gui/file/538e24051dc09c6fd44823b1a1ffdb943a232dce8a858d2c4ee535f57d966548](https://www.virustotal.com/gui/file/538e24051dc09c6fd44823b1a1ffdb943a232dce8a858d2c4ee535f57d966548)
Perhaps it might be better just to keep the editor in a rar or zip instead of an exe?
