### ISSUE TITLE
Coordinate Viewer error

### ISSUE THREAD

**Issue by DigitallyFidget** [goatfungus/NMSSaveEditor#789]
[Screenshot](https://i.imgur.com/F5ZjsK2.png) of issue where first number is always replaced with a zero. It doesn't matter what coords I enter, the address ends up wrong, and I end up in a wrong system. The screenshot is just an example for simplification. No matter what I do with the first value, it is treated as a zero, or star and water symbol.

**Comment by Devilin-Pixy** [comment]
The first glyph represents the planet, which is always set to 0 because you are supposed to end up in space of a system, most of the times anyway. The fact this changes to 0, should make no difference for the system location you will end up in. Do however make sure you are selecting the correct Galaxy. Your example of '111111111111' does get translated as expected, and has the correct result when checking the actual values within the Save Data JSON. Maybe provide an example where the result is actually believed to be faulty?

**Comment by goatfungus** [comment]
Correct. The coordinate viewer is meant to be an easy way to transport yourself (in your ship) to a different system. If the first number were not zero, you would end up INSIDE a planet because the editor doesn't know the terrain of the planet you are trying to go to.
