### ISSUE TITLE
Error when click tabs Discovery and Account in 1.13.9

### ISSUE THREAD

**Issue by China-AltF4** [goatfungus/NMSSaveEditor#811]
There is one of my save file, hope it will help author to solve the problem.
[save.zip](https://github.com/goatfungus/NMSSaveEditor/files/11365304/save.zip)
![屏幕截图 2023-05-01 201214](https://user-images.githubusercontent.com/117169376/235450754-a57a7315-4fa9-4b3a-bde7-0128afcb3961.png)

**Comment by China-AltF4** [comment]
And there is another problem.
![屏幕截图 2023-05-01 202356](https://user-images.githubusercontent.com/117169376/235451352-d0973e76-da0e-457a-803d-9f2acbd16d90.png)

**Comment by Darena-Bryant** [comment]
I am also having this issue. When clicking either tab, rather than going to the screen for that tab, nothing seems to happen. If I scroll around the panel a bit, pieces of the selected tab will appear: the scroll bar, then the menu, some of the other elements. But then the existing elements slowly vanish and have to also be scrolled over to make them reappear, and nothing ever fully becomes visible. Whatever tab I was in before clicking the offending tab remains in the panel as if in the background. I ran both the .bat and .jar files to see if it made a difference, but it doesn't.

**Comment by goatfungus** [comment]
I have tried opening your save files and I'm unable to reproduce the error.
Can you send me the log file? It might be something to do with the version of Java you are using.

**Comment by China-AltF4** [comment]
Here is the log file. I only installed jre Version 8u371 and I have reinstalled it again. I tried the "Beta: Use Unicode UTF-8 for worldwide language support", but it still couldn't solve the problem.
[log.zip](https://github.com/goatfungus/NMSSaveEditor/files/11371275/log.zip)

**Comment by goatfungus** [comment]
I have just released a new version that might help, but I'm not entirely sure since I still can't reproduce the Discovery tab issue.

As for the text display, it's probably using a font that does not fully support unicode characters, so it would be helpful if you could let me know which operating system you are using.

**Comment by goatfungus** [comment]
There are reports that this issue is still happening, but I'm not sure why. I have analyzed various offending saves, and all seem to work fine across multiple different Java versions on my PC.

I have added further debugging to the log output to help figure out what the cause is, so if you are still experiencing problems, please don't open another ticket, just post a message containing your saves and log file and I'll see what I can do.

**Comment by GrumpyKoala1966** [comment]
I just noticed that Java had an update April 18th 2023, could that be the reason?

I've updated it and is working well..

**Comment by China-AltF4** [comment]
The error has not been resolved in version 1.13.10. I'm Windows11 version-22H2. The current game version can also use version 1.12.0. I am only concerned that when version 1.12.0 cannot be used due to game updates, this error will not be resolved yet. Here is the new log file, it seems no difference.
[log.zip](https://github.com/goatfungus/NMSSaveEditor/files/11381384/log.zip)

**Comment by GrumpyKoala1966** [comment]
Thank you mate for all the work it's perfect..

**Comment by goatfungus** [comment]
It could be that the Beta version of Java is missing a few libraries that are present in other versions. I have noticed that the new look & feel system does report errors in quite a few places but it is able to recover just fine, so it's probably safe to simply ignore these errors and continue.
