### ISSUE TITLE
Account tab grayed out while using on MacOs

### ISSUE THREAD

**Issue by GrizzleMacThrornBody** [goatfungus/NMSSaveEditor#830]
Hi! It took me a little while to find where the save files are kept on a Mac, but as soon as I did, I was able to access ALMOST all of the features of the save editor-the exception being the account tab. At first I thought it was possibly because we (my 8 year-old and myself) hadn't purchased anything from the Quicksilver companion (he's already earned 2,200 quicksilver from running a weekend mission and a regular mission), so I bought a decal, set a restore point, quit the game and tried to access the account tab again, but that didn't work. Luckily, my son doesn't seem to want anything in particular from the shop (Golden Vector, gestures etc) right NOW, but I think he will at some point. This is obviously a BRAND new save, with the game having only come out for Mac yesterday. Is there an achievement he needs to get first? Perhaps this is a parity issue?

In any case, any help would be greatly appreciated! I'm happy to provide screenshots or any other information you might need. Thanks!

**Comment by MGJerry** [comment]
Hello, from what you mentioned above, I'm guessing that you guys are most likely are trying to either add more Quicksilver or items obtained from the Quicksilver Synthesis Shop. If you do, you can do that in the Exosuit tab (for more Quicksilver) or Discovery tab (for unlocking items).
The Account tab is for adding Seasonal rewards (from Expeditions), Twitch drops and preorder rewards from long ago. The reason it might be grayed out is either due to Mac version released recently has no support for those yet, or simply because the editor hasn't been updated to support it yet. If either is the case, you guys won't be needing that tab for a while.
Cheers.

**Comment by tarasis** [comment]
Account Tab works for me (old PC save, that I am now using on the Mac), and I have access to everything.

**Comment by GrizzleMacThrornBody** [comment]
> 

Thank you so much for your response, MGJerry! Sorry for not being clear. I completely forgot that the Discovery tab was where the Quicksilver items were found. If my son does end up wanting a Golden Vector or Utopia Speeder in the meantime, I'll just go into multiplayer and do the space station switcharoo with him from one of the saves where we unlocked them on my PC.

**Comment by GrizzleMacThrornBody** [comment]
> Account Tab works for me (old PC save, that I am now using on the Mac), and I have access to everything.

Awesome, trasis! I'll give that a try as well. Thank you so much!

**Comment by MGJerry** [comment]
> Account Tab works for me (old PC save, that I am now using on the Mac), and I have access to everything.

Yep, I borrowed a friend's MacBook to test this a few hours ago. Weirdly enough, the Account tab is only grayed out on a few newly created save on Mac (like 2/7 saves I made), not old / existing saves. I don't have enough technical knowledge to figure out the reason tho 🤷‍♂️
