### ISSUE TITLE
Some items in 'Known Products' are not appearing/working in-game.

### ISSUE THREAD

**Issue by VAL79** [goatfungus/NMSSaveEditor#86]
Hi GoatFungus, first-off thank you for this amazing tool, we all appreciate the hard work you have put into this program.

My issue as mentioned in the subject line is that there are a series of items within my 'Known Products' that simply do not appear as an item that can be constructed, and also the issue where some of those items if acquired in-game - legitimately - do not allow for extras to be constructed, the circle twirls when you hold E but it does not produce said item.

Let me get more specific with some examples: The main issue concerns an entire section of product 'Names' that are 'UI_TRADE_COMMODITY_1_NAME_L' through 'UI_TRADE_COMMODITY_5_NAME_L' and 'UI_TRADE_COMPONENT_1_NAME_L' through 'UI_TRADE_COMPONENT_5_NAME_L' that do not appear in-game despite being within the 'Known Products' section of the Save Editor. In addition to those 10 items that do not appear I also seem to have an issue with a select few of the 'Curiosity' items, specifically: GekNip, Gek Relic, Korvax Casing, Korvax Convergence Cube, Vy'keen Dagger, and the Vy'keen Effigy. Only the items that would be given to some of the NPCs at the end of conversations. I believe everything else on the list is working fine. I will be adding a picture so you can see how some of those items appear on my list - just in case that is the problem. For example instead of it saying 'Star Silk' it says 'UI_TRADE_COMMODITY_2_NAME_L' but the 'Curiosity' items are named correctly on the list.

![github](https://user-images.githubusercontent.com/20669479/43995758-84b650d8-9d82-11e8-8247-b88be3396448.png)

A friend of mine who also uses the Save Editor says his are all working without an issue. I do not know what could have caused this and was wondering if you or someone could help me troubleshoot/resolve the issue. Thank you for your time in this matter and Thank you once again for this amazing tool. Have an awesome day!

VAL79

**Comment by goatfungus** [comment]
The names of those items are not appearing correctly because HG have stuffed up some of the translation files. I'm waiting for them to fix this.

As for the known products section, it currently shows all products in game whether they are learnable or not. There is a good reason for this. Most learned products are normally acquired through random chance by visiting a manufacturing facility, and there is a special flag in the game files to distinguish them from other unlearnable products. However, there are a few that cannot be acquired in that way and are learned by completing a mission instead.

That means I have no option but to show them all in the editor, and leave it up to the user to choose. If the game doesn't allow it, just go back into the editor and remove it.
