### ISSUE TITLE
Name mapping not found

### ISSUE THREAD

**Issue by frostyhutt25** [goatfungus/NMSSaveEditor#914]
Hey there
Been couple months since I have used editor, using now on 1.4.4 and cant add items.
Comes up with 
Name mapping not found JBy
Name mapping not found Tx@

Cheers

**Comment by cjg67** [comment]
The name mapping is a harmless error that can be ignored.
You are going to need to give examples of things that you are not able to add so that they can check things out.
Anything that I needed to add has always worked, so I do not know why you would not be able to add items, unless the save file is corrupted in some way.
Developers need as much information as possible about bugs due to the many lines of code.
