### ISSUE TITLE
Feature Request - Move base computer  

### ISSUE THREAD

**Issue by alexnode** [goatfungus/NMSSaveEditor#93]
Do you think it is possible ? I have a very nice base and the computer is in the wrong place. Fantastic work so far.

**Comment by goatfungus** [comment]
I have found that moving the base computer makes the game think that it's an "old base" and needs to be rebuilt, so the only way to make this work is to translate all other base parts while leaving the computer in one place.

I am thinking of creating some basic templates in future to let users create indoor room structures around the base computer (since it can't be built inside certain rooms).

For example:
1) Placing it inside a round/rounded square room with teleporter (similar to how it was in Atlas Rises).
2) Placing it inside a cuboid room.

Another options I'm tossing up is the possibility of placing down a signal booster (which can go anywhere), and then getting the editor to swap the base computer and signal booster around while reformatting the entire base in the process. This is a big task though.

**Comment by TwoHeadedBoy** [comment]
So it looks like in the save file all of the parts belonging to any given base are given a position object relative to the base computer, right? There have been a few times where I've built a base first, slapped down the base computer, and then experienced issues editing or snapping new parts to the base. I can see now why it's not a simple thing to move the base computer; you'd have to take all of the base objects and remap them according to the new position. I've tried to do this myself and I can't make heads or tails of the other position objects in the base JSON structure.

**Comment by goatfungus** [comment]
You should have seen it prior to NEXT... all the object positions were translated to a special coordinate system that varied with every base location. I spent a lot of time getting a backup/restore feature working right and then they went and normalized all the coordinates (greatly simplifying it)! lol

Translating all the points wouldn't actually be too difficult as long as all objects are processed at once.

**Comment by alexnode** [comment]
Yes it sounds great to have it in a room, they should hire you!   I think they might change it / correct it , it seems a bit bizarre to have the computer outside , and to teleport next to your computer when you have a portal or landing pad. I noticed that the spaceship lands as close as possible with the computer .... and in impossible places if you build around it.  I loaded my old base and somehow i made a mess now i have the computer in the middle

**Comment by TwoHeadedBoy** [comment]
So I’ve done this before: I’ll plan a base up to where I know I’ll want the base computer, build a scaffolding of sorts up to the point where I have to drop it, then drop it and build the rest of the base. I’ve also had success removing the base computer from the JSON, fixing whatever needed fixing under the base computer, and then replacing the object in the JSON.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by goatfungus** [comment]
I have added the ability to move your base computer by swapping it with a signal booster (version 1.5.18). Hope this works for you :)
