### ISSUE TITLE
Question: Use Old Colours in ship window

### ISSUE THREAD

**Issue by Cythal** [goatfungus/NMSSaveEditor#95]
Thanks for this tool.

"use old colours" option is selected by default whenever I load a save. Please could you explain what it does and if it is on by default in the save before using the save editor. I do not seem to notice any difference in ship colours when it is not selected and when it is.

**Comment by goatfungus** [comment]
I don't know if it makes that much difference, and will probably remove it eventually, but it's there because that's what the game added to the save when NEXT was released. New ships acquired after NEXT have the box unticked, and pre-NEXT ships have it ticked. Adding it was an attempt to let people use seeds they grabbed off old websites.
