### ISSUE TITLE
raw JSON freezes

### ISSUE THREAD

**Issue by gibaotani** [goatfungus/NMSSaveEditor#98]
playing survival

when I click on the JSON option on the edit menu the application freezes before opening the editor. have to alt-tab to the .bat and ctrl+c to exit the program.

**Comment by VasilyMarkelov** [comment]
Same problem.
Normal mode playning.
NMSSaveEditor ver - 1.5.18

**Comment by goatfungus** [comment]
The control that renders the horrifically-large JSON file is a standard control but very inefficient. On many systems it works and on some it simply locks up. I am looking at alternatives.

**Comment by gibaotani** [comment]
Thanks for the reply. Tbh I'd be happy with a text file but I do hope you find what you're looking for.

**Comment by waldo3000** [comment]
I had this problem, too but I found a workaround.

I agree that there is a crazy amount of bloat in the save files, but that was not the problem in my case.  The problem was that there are some players that are using unexpected characters for their user name or when naming planets and other objects.

Specifically, there is a user that discovered a sector near the Galactic Hub named "Blitzk_", followed by some invalid ASCII values.  Those values in hex are:
F0 9D 95 83 F0 9D 95 8F F0 9D 95 8F.  I found that changing the F0 values to spaces makes the save file load properly.

I used nmssavetool to make these mods to the save file.

**Comment by goatfungus** [comment]
The application uses UTF-8 by default, but it is possible that the control the JSON editor uses may not support those characters when rendering each one using the label font. Not every font supports unicode. This is good info.

I will have a look at escaping all string values when showing the content in the JSON view, and see if that helps.

**Comment by goatfungus** [comment]
@waldo3000 I am wondering if you could try this experimental version for me (ignore the update warning):

[NMSSaveEditor.zip](https://github.com/goatfungus/NMSSaveEditor/files/2308141/NMSSaveEditor.zip)

I have added escapes for unicode characters so the JSON editor should work now.... however, I would not recommend pasting any non-ASCII characters in the editor box even though it allows it. I just need to see if this works for you.

**Comment by goatfungus** [comment]
The issues with unicode characters should be solved now (version 1.5.20). Please reopen this if the issue still persists.

**Comment by gibaotani** [comment]
thanks a lot for the solution, it works like a charm. also, i'd like to say that that was a pretty fast response time, good job and good luck!
