### ISSUE TITLE
Not all known word can be checkmarked

### ISSUE THREAD

**Issue by minyan** [goatfungus/NMSSaveEditor#99]
Either manually clicking the checkmark box or by pressing learn all.
Or is it by game design ?
Not all words have equivalent in other language ?
Like the word "Act" only available in Gek & Atlas, but not on Vy'keen & Korvax ?

Edit :
Another thing, only the Atlas word can't be uncheck even though the word can be learned.
Bug ?

**Comment by TwoHeadedBoy** [comment]
While I think this is due to not all languages having the equivalent word, I do find that some dialogue is still using the alien languages instead of the translation even though my save has every word learned. Has this happened to anyone else?

**Comment by goatfungus** [comment]
Not every word has a translation for each race, and some words don't even have a translation. The words data is pulled directly from the latest game files, so if there is a word missing it will be because HG haven't added it to their list yet.

The editor is only meant to let you tick the ones that are valid, with the exception of Atlas words (thanks for reporting the bug in the editor). This will be fixed in the next release.

**Comment by goatfungus** [comment]
Ok, should be fixed in 1.5.19
